Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /logout/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 6719
"GET /transactions/ HTTP/1.1" 302 0
"GET /login/?next=/transactions/ HTTP/1.1" 200 6457
"POST /login/?next=/transactions/ HTTP/1.1" 302 0
"GET /transactions/ HTTP/1.1" 200 34715
"GET /dashboard/ HTTP/1.1" 200 39785
"GET /admin/ HTTP/1.1" 200 9820
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 8015
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /logout/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 6719
"POST /login/ HTTP/1.1" 302 0
"GET /dashboard/ HTTP/1.1" 200 40038
"GET /static/assets/css/style.css HTTP/1.1" 304 0
"GET /static/assets/imgs/vaticanlogo.jpeg HTTP/1.1" 304 0
"GET /static/assets/imgs/theme/flag-us.png HTTP/1.1" 304 0
"GET /static/assets/imgs/theme/flag-fr.png HTTP/1.1" 304 0
"GET /static/assets/imgs/theme/flag-jp.png HTTP/1.1" 304 0
"GET /static/assets/js/vendors/jquery-3.6.0.min.js HTTP/1.1" 304 0
"GET /static/assets/css/vendors/normalize.css HTTP/1.1" 304 0
"GET /static/assets/css/vendors/bootstrap.css HTTP/1.1" 304 0
"GET /static/assets/imgs/theme/flag-cn.png HTTP/1.1" 304 0
"GET /static/assets/css/vendors/material-icon-round.css HTTP/1.1" 304 0
"GET /static/assets/css/vendors/perfect-scrollbar.css HTTP/1.1" 304 0
"GET /static/assets/css/vendors/select2.min.css HTTP/1.1" 304 0
"GET /static/assets/js/vendors/bootstrap.bundle.min.js HTTP/1.1" 304 0
"GET /static/assets/js/main.js?v=1.0.0 HTTP/1.1" 304 0
"GET /static/assets/js/vendors/select2.min.js HTTP/1.1" 304 0
"GET /static/assets/js/vendors/jquery.fullscreen.min.js HTTP/1.1" 304 0
"GET /static/assets/js/vendors/perfect-scrollbar.js HTTP/1.1" 304 0
"GET /static/assets/js/vendors/chart.js HTTP/1.1" 304 0
"GET /static/assets/js/custom-chart.js HTTP/1.1" 304 0
"GET /static/assets/imgs/people/avatar2.jpg HTTP/1.1" 304 0
"GET /static/assets/fonts/material-icon/MaterialIcons-Round.woff2 HTTP/1.1" 304 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /login/?next=/ HTTP/1.1" 200 6457
"GET /static/assets/css/style.css?v=1.0.0 HTTP/1.1" 304 0
"GET /static/assets/js/vendors/jquery-3.6.0.min.js HTTP/1.1" 304 0
"GET /static/assets/js/vendors/bootstrap.bundle.min.js HTTP/1.1" 304 0
"GET /static/assets/js/vendors/select2.min.js HTTP/1.1" 304 0
"GET /static/assets/css/vendors/normalize.css HTTP/1.1" 304 0
"GET /static/assets/css/vendors/perfect-scrollbar.css HTTP/1.1" 304 0
"GET /static/assets/css/vendors/material-icon-round.css HTTP/1.1" 304 0
"GET /static/assets/css/vendors/bootstrap.css HTTP/1.1" 200 257573
"GET /static/assets/css/vendors/select2.min.css HTTP/1.1" 304 0
"GET /static/assets/js/vendors/perfect-scrollbar.js HTTP/1.1" 304 0
"GET /static/assets/js/vendors/jquery.fullscreen.min.js HTTP/1.1" 304 0
"GET /static/assets/js/vendors/chart.js HTTP/1.1" 200 180403
"GET /static/assets/js/main.js?v=1.0.0 HTTP/1.1" 304 0
"GET /static/assets/js/custom-chart.js HTTP/1.1" 304 0
"GET /static/assets/imgs/theme/favicon.svg HTTP/1.1" 304 0
"POST /login/?next=/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 40038
"GET /static/assets/css/style.css HTTP/1.1" 304 0
"GET /static/assets/imgs/theme/flag-us.png HTTP/1.1" 304 0
"GET /static/assets/imgs/theme/flag-fr.png HTTP/1.1" 304 0
"GET /static/assets/imgs/theme/flag-jp.png HTTP/1.1" 304 0
"GET /static/assets/imgs/theme/flag-cn.png HTTP/1.1" 304 0
"GET /static/assets/imgs/people/avatar2.jpg HTTP/1.1" 304 0
"GET /static/assets/imgs/vaticanlogo.jpeg HTTP/1.1" 200 224289
"GET /static/assets/fonts/material-icon/MaterialIcons-Round.woff2 HTTP/1.1" 304 0
"GET / HTTP/1.1" 302 0
"GET /login/?next=/ HTTP/1.1" 200 6457
"GET /static/assets/js/vendors/jquery.fullscreen.min.js HTTP/1.1" 200 7012
"GET /static/assets/js/vendors/perfect-scrollbar.js HTTP/1.1" 200 38417
"GET /static/assets/css/style.css?v=1.0.0 HTTP/1.1" 200 68873
"GET /static/assets/js/vendors/select2.min.js HTTP/1.1" 200 68059
"GET /static/assets/js/vendors/jquery-3.6.0.min.js HTTP/1.1" 200 89503
"GET /static/assets/js/vendors/bootstrap.bundle.min.js HTTP/1.1" 200 80821
"GET /static/assets/js/main.js?v=1.0.0 HTTP/1.1" 200 1183
"GET /static/assets/js/custom-chart.js HTTP/1.1" 200 3482
"GET /static/assets/js/vendors/chart.js HTTP/1.1" 200 180403
"GET /static/assets/css/vendors/normalize.css HTTP/1.1" 200 6167
"GET /static/assets/css/vendors/perfect-scrollbar.css HTTP/1.1" 200 2598
"GET /static/assets/css/vendors/select2.min.css HTTP/1.1" 200 15445
"GET /static/assets/css/vendors/material-icon-round.css HTTP/1.1" 200 70132
"GET /static/assets/css/vendors/bootstrap.css HTTP/1.1" 200 257573
"GET /static/assets/imgs/theme/favicon.svg HTTP/1.1" 200 6924
"GET /manage-users/ HTTP/1.1" 200 33091
"POST /login/?next=/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 17659
"GET /static/assets/css/style.css HTTP/1.1" 200 68873
"GET /static/assets/imgs/theme/flag-fr.png HTTP/1.1" 200 554
"GET /static/assets/imgs/theme/flag-cn.png HTTP/1.1" 200 652
"GET /static/assets/imgs/theme/flag-jp.png HTTP/1.1" 200 573
"GET /static/assets/imgs/theme/flag-us.png HTTP/1.1" 200 656
"GET /static/assets/imgs/people/avatar2.jpg HTTP/1.1" 200 64728
"GET /static/assets/imgs/vaticanlogo.jpeg HTTP/1.1" 200 224289
"GET /static/assets/fonts/material-icon/MaterialIcons-Round.woff2 HTTP/1.1" 200 88376
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 8015
"GET /logout/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 6719
"POST /login/ HTTP/1.1" 302 0
"GET /dashboard/ HTTP/1.1" 200 26059
Watching for file changes with StatReloader
"GET /add-transaction/ HTTP/1.1" 200 21480
"POST /add-transaction/ HTTP/1.1" 302 0
"GET /transactions/ HTTP/1.1" 200 25889
"GET /dashboard/ HTTP/1.1" 200 26578
/Users/admin/Desktop/Accounting/account/forms.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/forms.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /dashboard/ HTTP/1.1" 200 26640
"GET /dashboard/ HTTP/1.1" 200 26640
"GET /dashboard/ HTTP/1.1" 200 26640
"GET /manage-users/ HTTP/1.1" 200 33091
"GET /add-transaction/ HTTP/1.1" 200 21490
"GET /dashboard/ HTTP/1.1" 200 26640
"GET /manage-branches/ HTTP/1.1" 200 29795
"GET /allocate-funds/ HTTP/1.1" 200 21307
"POST /allocate-funds/ HTTP/1.1" 302 0
"GET /fund-allocations/ HTTP/1.1" 200 22988
"GET /dashboard/ HTTP/1.1" 200 27447
- Broken pipe from ('127.0.0.1', 58923)
"GET /transactions/ HTTP/1.1" 200 26842
- Broken pipe from ('127.0.0.1', 58931)
"GET /add-transaction/ HTTP/1.1" 200 21490
"POST /add-transaction/ HTTP/1.1" 302 0
"GET /transactions/ HTTP/1.1" 200 28216
"GET /dashboard/ HTTP/1.1" 200 28201
/Users/admin/Desktop/Accounting/account/forms.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /allocate-funds/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/admin/Desktop/Accounting/account/views.py", line 321, in allocate_funds
    Transaction.objects.create(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        branch=main_branch,
        ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        created_by=request.user
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Desktop/Accounting/account/models.py", line 146, in save
    self.clean()
    ~~~~~~~~~~^^
  File "/Users/admin/Desktop/Accounting/account/models.py", line 139, in clean
    raise ValidationError(
    ...<3 lines>...
    )
django.core.exceptions.ValidationError: ["Insufficient funds. Current balance is ₦-800,000.00, but you're trying to spend ₦1,000,000.00. Available balance: ₦-800,000.00"]
"POST /allocate-funds/ HTTP/1.1" 500 90952
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 8015
"GET /allocate-funds/ HTTP/1.1" 200 21307
"GET /allocate-funds/ HTTP/1.1" 200 21307
"GET /dashboard/ HTTP/1.1" 200 40737
Internal Server Error: /allocate-funds/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/admin/Desktop/Accounting/account/views.py", line 321, in allocate_funds
    Transaction.objects.create(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        branch=main_branch,
        ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        created_by=request.user
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Desktop/Accounting/account/models.py", line 146, in save
    self.clean()
    ~~~~~~~~~~^^
  File "/Users/admin/Desktop/Accounting/account/models.py", line 139, in clean
    raise ValidationError(
    ...<3 lines>...
    )
django.core.exceptions.ValidationError: ["Insufficient funds. Current balance is ₦-800,000.00, but you're trying to spend ₦1,000,000.00. Available balance: ₦-800,000.00"]
"POST /allocate-funds/ HTTP/1.1" 500 91011
"GET /dashboard/ HTTP/1.1" 200 40758
/Users/admin/Desktop/Accounting/account/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/forms.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /dashboard/ HTTP/1.1" 200 42011
/Users/admin/Desktop/Accounting/account/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/forms.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /dashboard/ HTTP/1.1" 200 42320
"GET /add-transaction/ HTTP/1.1" 200 25764
"POST /add-transaction/ HTTP/1.1" 302 0
"GET /transactions/ HTTP/1.1" 200 43796
"GET /dashboard/ HTTP/1.1" 200 41691
"GET /add-transaction/ HTTP/1.1" 200 25764
"POST /add-transaction/ HTTP/1.1" 200 25804
"POST /add-transaction/ HTTP/1.1" 200 25804
"POST /add-transaction/ HTTP/1.1" 200 25804
"POST /add-transaction/ HTTP/1.1" 200 25804
"POST /add-transaction/ HTTP/1.1" 200 25804
"POST /add-transaction/ HTTP/1.1" 200 25804
"POST /add-transaction/ HTTP/1.1" 200 25804
"POST /add-transaction/ HTTP/1.1" 200 25804
"POST /add-transaction/ HTTP/1.1" 200 25804
"POST /add-transaction/ HTTP/1.1" 200 25804
"POST /add-transaction/ HTTP/1.1" 200 25804
"GET /dashboard/ HTTP/1.1" 200 29882
- Broken pipe from ('127.0.0.1', 59228)
"GET /dashboard/ HTTP/1.1" 200 41691
"GET /dashboard/ HTTP/1.1" 200 41686
"GET /transactions/ HTTP/1.1" 200 43538
"GET /add-transaction/ HTTP/1.1" 200 25764
"GET /transactions/ HTTP/1.1" 200 43538
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /transactions/ HTTP/1.1" 200 43436
"GET /transactions/ HTTP/1.1" 200 43436
"GET /transactions/ HTTP/1.1" 200 43436
"GET /add-income/ HTTP/1.1" 200 25765
"GET /add-income/ HTTP/1.1" 200 25765
"GET /add-expenditure/ HTTP/1.1" 200 25790
"GET /add-expenditure/ HTTP/1.1" 200 25790
"GET /manage-users/ HTTP/1.1" 200 32989
"GET /manage-branches/ HTTP/1.1" 200 29696
"GET /add-expenditure/ HTTP/1.1" 200 25790
"GET /add-expenditure/ HTTP/1.1" 200 25795
"GET /dashboard/ HTTP/1.1" 200 41584
"GET /fund-allocations/ HTTP/1.1" 200 24175
Internal Server Error: /add-income/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/admin/Desktop/Accounting/account/views.py", line 482, in add_income
    return render(request, 'add_transaction.html', {'form': form, 'transaction_type': 'income'})
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 976, in do_if
    nodelist = parser.parse(("endif",))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 710, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' == 'income' and 'trending_up' or 'trending_down'' from 'transaction_type == 'income' and 'trending_up' or 'trending_down''
"GET /add-income/ HTTP/1.1" 500 270365
"GET /add-income/ HTTP/1.1" 200 28189
"GET /add-income/ HTTP/1.1" 200 25770
"GET /add-income/ HTTP/1.1" 200 23587
"GET /add-income/ HTTP/1.1" 200 25770
"GET /transactions/ HTTP/1.1" 200 43436
"GET /dashboard/ HTTP/1.1" 200 29623
- Broken pipe from ('127.0.0.1', 59811)
"GET /transactions/ HTTP/1.1" 200 30121
"GET /transactions/ HTTP/1.1" 200 43436
"GET /manage-branches/ HTTP/1.1" 200 29696
"GET /transactions/ HTTP/1.1" 200 43436
"GET /transactions/ HTTP/1.1" 200 62514
"GET /transactions/ HTTP/1.1" 200 62514
"GET /transactions/ HTTP/1.1" 200 62514
"GET /transactions/ HTTP/1.1" 200 62514
"GET /transactions/ HTTP/1.1" 200 70093
"GET /transactions/ HTTP/1.1" 200 45795
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /transactions/ HTTP/1.1" 200 45803
"GET /transactions/ HTTP/1.1" 200 45803
Internal Server Error: /reports/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 1035, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'humanize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/admin/Desktop/Accounting/account/views.py", line 877, in reports
    return render(request, 'reports.html', context)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 1097, in load
    lib = find_library(parser, name)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 1037, in find_library
    raise TemplateSyntaxError(
    ...<5 lines>...
    )
django.template.exceptions.TemplateSyntaxError: 'humanize' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
"GET /reports/ HTTP/1.1" 500 260531
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /reports/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/admin/Desktop/Accounting/account/views.py", line 877, in reports
    return render(request, 'reports.html', context)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'mul'
"GET /reports/ HTTP/1.1" 500 337281
Internal Server Error: /reports/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/admin/Desktop/Accounting/account/views.py", line 877, in reports
    return render(request, 'reports.html', context)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'mul'
"GET /reports/ HTTP/1.1" 500 337281
/Users/admin/Desktop/Accounting/Accounting/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/admin/Desktop/Accounting/account/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /reports/ HTTP/1.1" 200 42542
"GET /dashboard/ HTTP/1.1" 200 41592
"GET /reports/ HTTP/1.1" 200 42542
"GET /dashboard/ HTTP/1.1" 200 41592
"GET /admin/ HTTP/1.1" 200 9820
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
"GET /reports/ HTTP/1.1" 200 42542
"GET /reports/?start_date=2025-08-01&end_date=2025-10-12&report_type=overview HTTP/1.1" 200 46195
"GET /dashboard/ HTTP/1.1" 200 41592
"GET /dashboard/ HTTP/1.1" 200 41592
"GET /reports/?start_date=2025-08-01&end_date=2025-10-12&report_type=overview HTTP/1.1" 200 46195
"GET /reports/?start_date=2025-08-01&end_date=2025-10-12&report_type=overview HTTP/1.1" 200 46195
"GET /reports/?start_date=2025-08-01&end_date=2025-10-12&report_type=overview HTTP/1.1" 200 46195
"GET /reports/?start_date=2025-08-01&end_date=2025-10-12&report_type=overview HTTP/1.1" 200 46195
"GET /reports/?start_date=2025-08-01&end_date=2025-10-12&report_type=overview HTTP/1.1" 200 46195
"GET /reports/?start_date=2025-08-01&end_date=2025-10-12&report_type=overview HTTP/1.1" 200 46194
